version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

# Port 4444 is used by selenium image to enable remote browser for tests.
# Port 5900 is used for accessing running remote browser from outside with VNC viewer.
  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - "4444:4444"
      - "5900:5900"

