# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bba25c5e9fcd8f874068bfb0de8275960df915554e3259c39ef51269b96d605c688b9eabd2be393cfa373fc79c425970ede08d24867ae4c1f5ccbbca32d9e6e

test:
  secret_key_base: 4e0a0ca8cf636bbc4360fcd99f62ac8ae32d92e1b7c3da23a6b8217460ae8ca198dcedf77ccbcbe5817480767a08f3b54ca4efa4e7a7723b2827348c683051c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
